# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Frank Wildenburg # Change this to your book title.
author: Frank Wildenburg # Change this to your name (or your team/organization name).

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  analytics:
    google_analytics_id: G-VZZ8DCTMLV

logo: docs/images/frank.jpeg

sphinx:
  extra_extensions:
    # This is to work around the bug of no syntax highlighting
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      # This is for plotly to work
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
